version: 2

build:
  os: rockylinux:9
  tools:
    python: "3.9"

python:
   version: 3.9
   install:
   - requirements: requirements.txt

mkdocs:
  configuration: mkdocs.yml

submodules:
  include: all
  recursive: true
