site_name: Xrootd HowTos
docs_dir: docs
site_dir: site
plugins:
  - include-markdown
  - search:
      min_search_length: 2
nav:
    - 'About': README.md
    - 'Compile Xrootd on CentOS': Compile.md
    - '3rd Party Copy for Posix & Object Store': tpc/README.md
    - 'Erasure Coding': ec/README.md
    - 'Tape Endpoint Demo' : preplib4tape/README.md
    - 'Network IO Monitoring Dashboard' : NetIOmon/README.md
    - 'Customizing Systemd Service' : systemd/README.md
    - 'Redirector in Kubernetes' : k8s/xrdrdr/README.md
theme: 
  name: readthedocs
  plugins: 
#  highlightjs: false
# more options: https://www.mkdocs.org/user-guide/choosing-your-theme/#readthedocs
